## 모듈과 패키지

In [1]:
# 모듈은 변수, 함수, 클래스를 담고 있는 파일 (.py)
# 패키지는 여러 모듈을 묶은 것 (폴더)
# import 모듈
# import 모듈1, 모듈2
# 모듈.변수
# 모듈.함수()
# 모듈.클래스()

In [1]:
# import math # math라는 모듈이 있어요
# print(math.pi)
# print(math.sqrt(4)) # sqrt는 제곱근 구해줌

import math
print(math.pi)
print(math.sqrt(4))


3.141592653589793
2.0


In [2]:
# import math as m # math를 가져오는 데 m 이라는 이름으로 가져온다
# print(m.pi)
# print(m.sqrt(4))

import math as m
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [3]:
# from math import pi, sqrt
# print(pi)
# print(sqrt(4))

from math import pi, sqrt
print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [4]:
# from math import * # * 이 all 이란 뜻
# print(pi)
# print(sqrt(4))
# print(sin(pi))

from math import *
print(pi)
print(sqrt(4))
print(sin(pi))

3.141592653589793
2.0
1.2246467991473532e-16


In [5]:
# from math import sqrt as s
# print(s(4))

from math import sqrt as s
print(s(4))

2.0


In [6]:
# from math import sqrt as s, pi as p
# print(p)
# print(s(4))

from math import sqrt as s, pi as p
print(p)
print(s(4))

3.141592653589793
2.0


In [ ]:
# import 패키지
# import 패키지.모듈1
# import 패키지.모듈1, 패키지.모듈2
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [7]:
# import numpy as np # numpy는 라이브러리(패키지와 모듈들을 모아놓음)다 (numerical python)
# a=np.array([1,2,3])
# print(a)

import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [8]:
# import numpy.random
# print(numpy.random.randn(3,3)) # Normal distribution, (3,3)은 3행 3열 짜리를 의미

import numpy.random
print(numpy.random.randn(3, 3))

[[ 0.64483569  0.75382425 -0.91943138]
 [ 1.25091922  0.48443387 -1.08735862]
 [-0.73098274  0.32421063  0.50061557]]


In [9]:
# import numpy.random as nr
# print(nr.randn(3,3))

import numpy.random as nr
print(nr.randn(3,3))

[[ 1.10155102 -1.22618078 -1.40795102]
 [-1.42428359 -0.76076181 -0.20581202]
 [-1.61100466 -1.55177883  0.68791867]]


In [10]:
# from numpy.random import randn
# print(randn(3,3))

from numpy.random import randn
print(randn(3,3))

[[ 0.80806746  0.13609396 -0.26524677]
 [-1.02902437  1.59168119 -0.36933289]
 [ 0.66671381  0.8367227  -1.31615107]]


In [11]:
# from numpy.random import *
# print(rand(3,3)) # uniform distribution

from numpy.random import *
print(rand(3, 3))

[[0.05763604 0.1471734  0.46428181]
 [0.57191875 0.05837074 0.79488502]
 [0.16428521 0.22971808 0.51870787]]


In [12]:
# from numpy.random import randn as rn
# print(rn(3,3))

from numpy.random import randn as rn
print(rn(3,3))

[[-0.04688386  0.15079833 -0.0483566 ]
 [-1.29652703  0.04672459  0.51030998]
 [ 0.5178345   0.58961061  1.6124332 ]]


In [13]:
# from numpy.random import randn as rn, rand as r
# print(rn(3,3))
# print(r(3,3))

from numpy.random import randn as rn, rand as r
print(rn(3,3))
print(r(3,3))

[[ 0.36500786  1.97369842  0.47051768]
 [-1.36556774 -0.07164895 -0.40966033]
 [ 1.0638947   0.39548773  0.37633026]]
[[0.34112591 0.36221066 0.91965269]
 [0.17378394 0.84352013 0.43582774]
 [0.1296695  0.56396602 0.53599482]]
[[ 1.53844943  1.57305778 -1.57736546]
 [ 0.26147219 -1.67685983 -1.05262674]
 [ 0.14387211 -0.65577157 -0.4813241 ]]
[[0.45424994 0.6315613  0.345634  ]
 [0.27662927 0.59005874 0.01828694]
 [0.26621399 0.63766559 0.59882621]]


## numpy 본격적으로

In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
b=np.array([1,2, 3.1   , 4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
float64


In [1]:
A=np.array([[1,2,3],[3,4,5]]) # 이 셀부터는 import numpy as np 는 실행 했다 치고 작성
# A=np.array([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.size) # 전체 성분의 수

NameError: ignored

In [ ]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros( (3,3) )) # 튜플을 입력으로! 그냥 np.zeros(3,3)은 안돼요
print(np.arange(3,10,2)) # range랑 같은데 array로 만들어줌
print(np.arange(0,1,0.1)) # 소수점 가능
print(np.linspace(0,1,10, endpoint=False)) # 0 에서부터 1 포함(default) 10개로

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c) # 드디어! 양 옆으로 길어지는 게 아닌 벡터의 합이 나옴!

[5 7 9]


In [ ]:
A=np.array([[1,2,3],[1,2,3]])
B=np.array([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C) 
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product)
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]

[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
[[16 25 36]
 [ 1  1  1]]


In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


## numpy 의 인덱싱 슬라이스

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9]) 
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0]) 
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 행렬에 대한 인덱싱과 슬라이싱
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
B=[[1,2,3,4], [5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # error!
print(A[1,:]) # 1 행, 전부
print(A[1,0:3:2])
print(A[:,2]) # 전부, 2 열
print(A[:][2])

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
[3 6 9]


In [ ]:
# 3차원 행렬 인덱싱
A=np.array([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,   
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A.shape) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다.
print(A[0,1,2])

a=np.array([[[1,2,3,4]]])
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6


In [ ]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=np.array([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A==3] = 100
print(A) # 그러면 이런 것도 가능하다! (3과 같은 애를 100으로 바꿔줘)

A=np.array([[1,2],[3,4],[5,6],[7,8]])
B=np.array([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=np.array([1,2,3,4])
print(b[[True,True,False,False]])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2 100   4]
 [  5 100   7 100]]
[[1 2]
 [7 8]]
[1 2]


In [ ]:
# array로 인덱싱
a=np.array([1,2,3,4,5])
A=a[2]
print(A)
A=a[ np.array(2) ] # np.array를 안에다가?
print(A)
A=a[ np.array([2,3,4]) ]
print(A)
A=a[ np.array([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=np.array([[1,2,3],[4,5,6]])
print(a[0])
A=a[ np.array([[0,1],[1,1]]) ]
print(A.shape) # 예를 들어, a[0] = array([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

3
3
[3 4 5]
[[3 3 3]
 [4 4 4]]
[1 2 3]
(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [4 5 6]]]


In [ ]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ array(bool) ] => A와 같은 shape을 가지는 array형 bool이 어디에 True를 가지고 있냐
print(A[ np.array([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,False], [False,True] ])
# 4. A[ array ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ np.array([1,1,2,2,2]) ])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2
[2]
[2]
[2]
[[3 4]
 [3 4]
 [5 6]
 [5 6]
 [5 6]]


## numpy의 여러 함수들

In [ ]:
A=np.random.randn(3,3) # 여긴 튜플로 안줘도 됨
B=np.random.rand(3,3)
print(A)
print(B)
print(A[A[:,0]<0,:]) # 0 번째 열이 음수인 행들

[[-1.67088393  1.20670741  0.54234205]
 [ 1.36383223 -0.25169022  0.41783062]
 [ 0.47468166 -0.92600609  0.21809043]]
[[0.89976423 0.07464855 0.03793748]
 [0.83516205 0.6430013  0.08906904]
 [0.56968633 0.28267234 0.7287293 ]]
[[-1.67088393  1.20670741  0.54234205]]


In [ ]:
A=np.random.randn(3,3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A)))
print(np.exp(A))
print(np.log(np.abs(A)))
print(np.log(np.exp(1))) # np.exp(1) = e^1
print(np.log10(10))
print(np.log2(2))
print(np.round(A)) # 반올림
print(np.round(A,2)) # 소수점 둘째자리까지
print(np.floor(A)) # 내림
print(np.ceil(A)) # 올림

[[ 0.39310191  1.09891698 -1.14853052]
 [ 1.42179433 -0.71248915 -0.58522194]
 [-1.35936487 -0.97865628  0.31967606]]
[[0.39310191 1.09891698 1.14853052]
 [1.42179433 0.71248915 0.58522194]
 [1.35936487 0.97865628 0.31967606]]
[[0.6269784  1.04829241 1.07169516]
 [1.19239017 0.84409072 0.764998  ]
 [1.16591804 0.98927058 0.56539903]]
[[1.48156937 3.0009142  0.3171024 ]
 [4.14455044 0.49042194 0.55698223]
 [0.25682384 0.37581575 1.37668173]]
[[-0.93368638  0.09432513  0.13848331]
 [ 0.35191968 -0.33899059 -0.53576412]
 [ 0.30701758 -0.02157479 -1.1404471 ]]
1.0
1.0
1.0
[[ 0.  1. -1.]
 [ 1. -1. -1.]
 [-1. -1.  0.]]
[[ 0.39  1.1  -1.15]
 [ 1.42 -0.71 -0.59]
 [-1.36 -0.98  0.32]]
[[ 0.  1. -2.]
 [ 1. -1. -1.]
 [-2. -1.  0.]]
[[ 1.  2. -1.]
 [ 2. -0. -0.]
 [-1. -0.  1.]]


In [ ]:
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
print(np.tan(np.pi/4))
print(np.tanh(-10))

0.49999999999999994
0.5000000000000001
0.9999999999999999
-0.9999999958776927


In [ ]:
np.nan # not a number
# np.log(-1)
print(np.isnan([1,2,np.nan,3,4]))
print(np.isinf([1,2,3,4,np.inf]))

[False False  True False False]
[False False False False  True]


In [ ]:
A=np.random.randn(3,4)
print(A)
print(np.max(A))
print(np.max(A,axis=0))
print(np.max(A,axis=1)) # 1D array로 바꿔버림
print(np.max(A,axis=0, keepdims=True))
print(np.max(A,axis=1, keepdims=True)) # 3 행 1열 짜리 2D array
print(np.min(A))
print(np.min(A,axis=0))
print(np.min(A,axis=1))
print(np.argmax(A))
print(np.argmax(A,axis=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A,axis=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

[[-0.60111745  0.65358943  0.33652573 -0.45064509]
 [ 0.56531042 -0.72526529 -0.81906752  0.34428911]
 [-1.63712718 -0.93759457 -0.23680838 -1.58124809]]
0.6535894288117479
[0.56531042 0.65358943 0.33652573 0.34428911]
[ 0.65358943  0.56531042 -0.23680838]
-1.6371271793873285
[-1.63712718 -0.93759457 -0.81906752 -1.58124809]
[-0.60111745 -0.81906752 -1.63712718]
1
[1 0 0 1]
[1 0 2]


In [ ]:
a=np.random.randn(6,1)
print(a)
a_sorted=np.sort(a,axis=0)
print(a_sorted)
print(np.flipud(a_sorted))

[[-0.65515746]
 [-0.44962029]
 [ 3.20124317]
 [ 0.68946336]
 [ 0.07725051]
 [ 1.18731823]]
[[-0.65515746]
 [-0.44962029]
 [ 0.07725051]
 [ 0.68946336]
 [ 1.18731823]
 [ 3.20124317]]
[[ 3.20124317]
 [ 1.18731823]
 [ 0.68946336]
 [ 0.07725051]
 [-0.44962029]
 [-0.65515746]]


In [ ]:
A=np.random.randn(3,4)
print(A)
print(np.sum(A))
print(np.sum(A,axis=1))
print(np.sum(A,axis=1,keepdims=True))
print(np.mean(A))
print(np.mean(A,axis=1))
print(np.mean(A,axis=1,keepdims=True))
print(np.std(A)) # standard deviation 표준 편차

print(A.sum(axis=1, keepdims=True))
print(A.mean(axis=1, keepdims=True))
print(A.std())

[[-1.75981859  0.36521311 -1.52186851 -0.59986822]
 [-1.33080073  0.05467037 -0.60351552 -2.19124035]
 [-1.13160495  1.79967378  0.57823896 -1.01418047]]
-7.3551011293919935
[-3.51634221 -4.07088624  0.23212732]
[[-3.51634221]
 [-4.07088624]
 [ 0.23212732]]
-0.6129250941159995
[-0.87908555 -1.01772156  0.05803183]
[[-0.87908555]
 [-1.01772156]
 [ 0.05803183]]
1.0885848676263121


In [ ]:
A=np.random.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

[3 4 1 1 4 2 4 4 4 1 1 3]
(12,)
[[[3 4 1]
  [1 4 2]]

 [[4 4 4]
  [1 1 3]]]
3


In [ ]:
a=np.array([1,2,3])
b=np.array([2,2,1])
print(np.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose()@b)
print(a.T@b)

A=np.random.randn(4,3,6)
print(A.transpose(0,2,1).shape)

9
[[9]]
[[9]]
(4, 6, 3)


In [ ]:
A=np.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)
(2, 2, 5)
(1, 20)
(20, 1)


In [ ]:
x=np.random.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape) 
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(2, 3, 4, 5)
(3, 4, 6)
(3, 4, 6)


In [ ]:
A=np.ones((3,4))
B=np.zeros((3,4))
C=np.vstack([A,B])
D=np.hstack([A,B])
E=np.block([[A],[B]])
F=np.block([A,B])
G=np.block([ [[A]], [[B]] ])

print(C)
print(D)
print(E)
print(F)
print(G)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]


In [ ]:
A = np.random.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(axis=(0,2,4,5)).shape)

(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [ ]:
A = np.random.randn(3,4)
A1 = A[np.newaxis,...] # np.newaxis is None <- True
print(A1.shape)
A2 = A[...,np.newaxis]
print(A2.shape)
A3 = A[:,np.newaxis,:]
print(A3.shape)
A1 = np.expand_dims(A,axis=0)
print(A1.shape)
A2 = np.expand_dims(A,axis=2)
print(A2.shape)
A3 = np.expand_dims(A,axis=1)
print(A3.shape)
A1 = A.reshape(1,3,4)
print(A1.shape)
A2 = A.reshape(3,4,1)
print(A2.shape)
A3 = A.reshape(3,1,4)
print(A3.shape)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
